-- Web push: subscriptions, the outbox that queues what gets sent, and the storms
-- triggers that fill it.
--
-- Two halves, on purpose:
--   * storms  -> automatic. Rows arrive one at a time as a season runs, so triggers
--                on this table enqueue formation / upgrade / record events.
--   * names   -> manual. isretired, isreplaced and suggestednames.ischosen are all
--                updated in one batch each May off the Typhoon Committee report. A
--                row-level trigger cannot tell when that batch is finished, so there
--                is deliberately no trigger here — the app enqueues one digest when
--                the announce button is pressed.
--
-- Every enqueue is guarded on recency (see push_is_recent) so backfilling historical
-- seasons never notifies anyone, and deduplicated on dedupekey so re-editing a row
-- cannot send the same thing twice.

SET search_path TO catfisha_typhoons, public;

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

-- What a subscriber opted into. 'storms' runs a few times a month in season;
-- 'names' is the annual committee digest. Very different volumes, so they are
-- separate toggles rather than one on/off switch.
CREATE TYPE push_topic AS ENUM ('storms', 'names');

CREATE TYPE pushoutbox_kind AS ENUM (
    'formed',       -- a new storm row appeared with no enddate
    'intensified',  -- intensity moved up the scale
    'strongest',    -- isstrongest flipped true: new record for that name
    'seasonfirst',  -- isfirst flipped true
    'seasonlast',   -- islast flipped true
    'committee'     -- the annual retired/replaced digest, enqueued by hand
);

-- Queued rows are not sent until a drain runs, which leaves a window to cancel a
-- push caused by a typo before it reaches anyone.
CREATE TYPE pushoutbox_status AS ENUM ('pending', 'sent', 'cancelled');

-- ---------------------------------------------------------------------------
-- pushsubscriptions — one row per browser that granted permission
-- ---------------------------------------------------------------------------

CREATE TABLE pushsubscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint text NOT NULL UNIQUE,  -- push service URL; the browser's identity for this subscription
    p256dh text NOT NULL,           -- client public key, from the subscription's getKey('p256dh')
    auth text NOT NULL,             -- client auth secret, from getKey('auth')
    topics push_topic[] NOT NULL DEFAULT ARRAY['storms', 'names']::push_topic[],
    useragent text,                 -- purely for debugging which platforms are subscribed
    createdat timestamptz NOT NULL DEFAULT now(),
    updatedat timestamptz NOT NULL DEFAULT now(),
    -- A subscription is dropped as soon as the push service reports it gone (404/410),
    -- so there is no need to track failures beyond that.
    CONSTRAINT pushsubscriptions_topics_not_empty CHECK (cardinality(topics) > 0)
);

CREATE INDEX idx_pushsubscriptions_topics ON pushsubscriptions USING gin (topics);

-- ---------------------------------------------------------------------------
-- pushoutbox — the queue
-- ---------------------------------------------------------------------------

CREATE TABLE pushoutbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind pushoutbox_kind NOT NULL,
    topic push_topic NOT NULL,
    -- Natural key for the event, e.g. "intensified:591:5". Unique, so a trigger that
    -- fires twice for the same real-world event only ever queues one notification.
    dedupekey text NOT NULL UNIQUE,
    title text NOT NULL,
    body text NOT NULL,
    url text NOT NULL,              -- app-relative deep link, e.g. "/info/yagi/"
    status pushoutbox_status NOT NULL DEFAULT 'pending',
    createdat timestamptz NOT NULL DEFAULT now(),
    sentat timestamptz,
    sentcount integer,              -- subscriptions successfully delivered to
    CONSTRAINT pushoutbox_sentat_requires_sent
        CHECK ((status = 'sent') = (sentat IS NOT NULL))
);

CREATE INDEX idx_pushoutbox_pending ON pushoutbox (createdat) WHERE status = 'pending';

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

-- True when a storm is recent enough that an edit to it is live curation rather than
-- backfill. Everything the triggers do is gated on this: without it, filling in dates
-- for the 2005 season would push a few hundred notifications.
CREATE FUNCTION push_is_recent(p_startdate date, p_days integer) RETURNS boolean
LANGUAGE sql STABLE AS $$
    SELECT p_startdate IS NOT NULL
       AND p_startdate >= CURRENT_DATE - (p_days || ' days')::interval
       -- A start date in the future is a typo, not a storm.
       AND p_startdate <= CURRENT_DATE + INTERVAL '2 days';
$$;

-- Mirrors INTENSITY_LABEL in src/lib/constants so notification text reads the same as
-- the app. 'NT' is deliberately absent: those storms never generate notifications.
CREATE FUNCTION push_intensity_label(p_intensity storms_intensity) RETURNS text
LANGUAGE sql IMMUTABLE AS $$
    SELECT CASE p_intensity
        WHEN '5'   THEN 'Category 5 Super Typhoon'
        WHEN '4'   THEN 'Category 4 Typhoon'
        WHEN '3'   THEN 'Category 3 Typhoon'
        WHEN '2'   THEN 'Category 2 Typhoon'
        WHEN '1'   THEN 'Category 1 Typhoon'
        WHEN 'STS' THEN 'Severe Tropical Storm'
        WHEN 'TS'  THEN 'Tropical Storm'
        WHEN 'TD'  THEN 'Tropical Depression'
    END;
$$;

-- "12W" — the JTWC number padded and suffixed with the position's basin letter.
-- NULL when the storm has no number yet, which is normal early in its life.
CREATE FUNCTION push_designation(p_position integer, p_jtwcnumber integer) RETURNS text
LANGUAGE sql STABLE AS $$
    SELECT LPAD(p_jtwcnumber::text, 2, '0') || p.suffix::text
    FROM positions p
    WHERE p.id = p_position AND p_jtwcnumber IS NOT NULL;
$$;

CREATE FUNCTION push_enqueue(
    p_kind pushoutbox_kind,
    p_topic push_topic,
    p_dedupekey text,
    p_title text,
    p_body text,
    p_url text
) RETURNS void
LANGUAGE sql AS $$
    INSERT INTO pushoutbox (kind, topic, dedupekey, title, body, url)
    VALUES (p_kind, p_topic, p_dedupekey, p_title, p_body, p_url)
    ON CONFLICT (dedupekey) DO NOTHING;
$$;

-- ---------------------------------------------------------------------------
-- storms triggers
-- ---------------------------------------------------------------------------

CREATE FUNCTION storms_push_notify() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    v_url text := '/info/' || lower(NEW.name) || '/';
    v_designation text;
    v_label text;
    v_suffix text;
BEGIN
    -- 'NT' storms were never tracked by the JTWC and are only ever entered years after
    -- the fact, so they never notify — in either direction of an edit.
    IF NEW.intensity = 'NT' THEN
        RETURN NULL;
    END IF;

    v_label := push_intensity_label(NEW.intensity);
    v_designation := push_designation(NEW.position, NEW.jtwcnumber);
    v_suffix := CASE WHEN v_designation IS NULL THEN '' ELSE ' (' || v_designation || ')' END;

    IF TG_OP = 'INSERT' THEN
        -- A storm still in progress: this is the formation notification.
        IF NEW.enddate IS NULL AND push_is_recent(NEW.startdate, 21) THEN
            PERFORM push_enqueue(
                'formed', 'storms',
                'formed:' || NEW.id,
                NEW.name || ' has formed',
                v_label || ' ' || NEW.name || v_suffix
                    || ' is now active in the western Pacific.',
                v_url
            );
        END IF;
    ELSIF TG_OP = 'UPDATE' THEN
        -- Upgrades only. A downgrade is a reanalysis correction and is not worth an
        -- interrupt; OLD.intensity = 'NT' is a data fix, not an upgrade.
        IF NEW.intensity > OLD.intensity AND OLD.intensity <> 'NT'
           AND push_is_recent(NEW.startdate, 21) THEN
            PERFORM push_enqueue(
                'intensified', 'storms',
                'intensified:' || NEW.id || ':' || NEW.intensity,
                NEW.name || ' is now a ' || v_label,
                'Upgraded from ' || push_intensity_label(OLD.intensity) || '.',
                v_url
            );
        END IF;

        IF NEW.isstrongest AND NOT OLD.isstrongest AND push_is_recent(NEW.startdate, 21) THEN
            PERFORM push_enqueue(
                'strongest', 'storms',
                'strongest:' || NEW.id,
                'A new record for the name ' || NEW.name,
                NEW.name || ' (' || NEW.year || ') is now the strongest storm ever to '
                    || 'carry this name.',
                v_url
            );
        END IF;
    END IF;

    -- Season bookends get a wider window: islast in particular is filled in weeks after
    -- the closing storm, once the season is confirmed over.
    IF TG_OP = 'UPDATE' AND NEW.isfirst AND NOT OLD.isfirst
       AND push_is_recent(NEW.startdate, 60) THEN
        PERFORM push_enqueue(
            'seasonfirst', 'storms',
            'seasonfirst:' || NEW.id,
            NEW.name || ' opens the ' || NEW.year || ' season',
            'First named storm of the ' || NEW.year || ' western Pacific season.',
            v_url
        );
    END IF;

    IF TG_OP = 'UPDATE' AND NEW.islast AND NOT OLD.islast
       AND push_is_recent(NEW.startdate, 60) THEN
        PERFORM push_enqueue(
            'seasonlast', 'storms',
            'seasonlast:' || NEW.id,
            NEW.name || ' closes the ' || NEW.year || ' season',
            'Last named storm of the ' || NEW.year || ' western Pacific season.',
            v_url
        );
    END IF;

    RETURN NULL;
END;
$$;

CREATE TRIGGER storms_push_notify_insert
    AFTER INSERT ON storms
    FOR EACH ROW EXECUTE FUNCTION storms_push_notify();

CREATE TRIGGER storms_push_notify_update
    AFTER UPDATE ON storms
    FOR EACH ROW
    WHEN (
        OLD.intensity IS DISTINCT FROM NEW.intensity
        OR OLD.isstrongest IS DISTINCT FROM NEW.isstrongest
        OR OLD.isfirst IS DISTINCT FROM NEW.isfirst
        OR OLD.islast IS DISTINCT FROM NEW.islast
    )
    EXECUTE FUNCTION storms_push_notify();
