-- Schema of the typhoon database, with one example row per table.
-- The example rows form a single connected set — position 19 and the name Yagi —
-- so the file loads top to bottom with every foreign key satisfied.

CREATE SCHEMA IF NOT EXISTS catfisha_typhoons;

SET search_path TO catfisha_typhoons, public;

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

-- Saffir-Simpson category for typhoons ('1'-'5'), below-typhoon strength otherwise.
-- 'NT' is not a step on the scale: the JTWC never issued warnings on that storm, so it has
-- no category at all. It sorts first so the enum order still runs weakest to strongest.
CREATE TYPE storms_intensity AS ENUM ('NT', 'TD', 'TS', 'STS', '1', '2', '3', '4', '5');

-- JTWC basin letter appended to the storm number, e.g. jtwcnumber 11 + 'W' -> "11W".
CREATE TYPE suffix AS ENUM ('W', 'E', 'B', 'C');

-- Why a name left rotation.
CREATE TYPE typhoonnames_retirementreason AS ENUM ('destructive', 'language', 'misspell', 'special');

-- ---------------------------------------------------------------------------
-- imagelicenses — license lookup shared by typhoonnames.image and suggestednames.image
-- ---------------------------------------------------------------------------

CREATE TABLE imagelicenses (
    id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name character varying NOT NULL UNIQUE,  -- e.g. "CC BY 3.0"
    url character varying                    -- NULL for licenses with no canonical deed URL
);

INSERT INTO imagelicenses (id, name, url) OVERRIDING SYSTEM VALUE
VALUES
    (5, 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'),
    (8, 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0');

-- ---------------------------------------------------------------------------
-- positions — the 140 slots of the Western Pacific naming list
-- ---------------------------------------------------------------------------

-- A position is a fixed slot in the rotation, owned by one contributing country.
-- Both typhoonnames and storms hang off it, which is how a storm gets its country
-- without duplicating it per row.
CREATE TABLE positions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country character varying(20) NOT NULL,
    suffix suffix DEFAULT 'W' NOT NULL
);

INSERT INTO positions (id, country, suffix)
VALUES (19, 'Japan', 'W');

-- ---------------------------------------------------------------------------
-- typhoonnames — every name that has ever held a position, current or retired
-- ---------------------------------------------------------------------------

-- A position accumulates rows over time: the name in rotation today plus each
-- name that was retired out of that slot. isretired distinguishes them.
CREATE TABLE typhoonnames (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(10) NOT NULL,
    meaning character varying(255) NOT NULL,
    tag character varying(40) NOT NULL,             -- category of the meaning, e.g. "Animal", "Flower"
    "position" integer NOT NULL,
    isretired boolean DEFAULT false NOT NULL,
    -- True once a replacement name has actually been selected; a name can be retired
    -- while the committee is still deciding, in which case suggestednames holds the candidates.
    isreplaced boolean DEFAULT false NOT NULL,
    replacementname character varying(10) DEFAULT '' NOT NULL,  -- '' for names still in rotation
    note text,
    language character varying(20) NOT NULL,        -- language the name comes from, e.g. "Japanese"
    lastyear integer,                               -- final season the name was used; NULL while in rotation
    image character varying(255) DEFAULT NULL,
    description character varying(255) DEFAULT '' NOT NULL,
    imageauthor character varying,
    imagesourceurl character varying,
    imagelicenseid smallint,
    ipa text DEFAULT 'NULL',                        -- default is the literal string 'NULL', not SQL NULL
    originaltext text,                              -- name in its native script, e.g. ヤギ
    pronunciationfile text,                         -- filename under public/, e.g. "Yagi.mp3"
    retirementreason typhoonnames_retirementreason, -- NULL exactly when the name is still in rotation
    -- A name has a retirement reason exactly when it is retired.
    CONSTRAINT typhoonnames_retirementreason_requires_retired
        CHECK ((retirementreason IS NULL) = (NOT isretired)),
    CONSTRAINT typhoonnames_ibfk_1 FOREIGN KEY ("position")
        REFERENCES positions(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT typhoonnames_imagelicenseid_fkey FOREIGN KEY (imagelicenseid)
        REFERENCES imagelicenses(id)
);

CREATE INDEX idx_17781_position ON typhoonnames USING btree ("position");

INSERT INTO typhoonnames (
    id, name, meaning, tag, "position", isretired, isreplaced,
    replacementname, note, language, lastyear, image, description,
    imageauthor, imagesourceurl, imagelicenseid, ipa, originaltext,
    pronunciationfile, retirementreason
)
VALUES (
    19, 'Yagi', 'Capricorn, goat', 'Animal', 19, true, true,
    'Tomo', '', 'Japanese', 2024,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Feral_Goats_at_St_Tudno%27s_Churchyard_-_geograph.org.uk_-_2426882.jpg/960px-Feral_Goats_at_St_Tudno%27s_Churchyard_-_geograph.org.uk_-_2426882.jpg',
    '', 'David Dixon',
    'https://commons.wikimedia.org/wiki/File:Feral_Goats_at_St_Tudno''s_Churchyard_-_geograph.org.uk_-_2426882.jpg',
    5, '[ja̠ɡʲi]', 'ヤギ', 'Yagi.mp3', 'destructive'
);

-- ---------------------------------------------------------------------------
-- storms — one row per named storm occurrence
-- ---------------------------------------------------------------------------

-- Joined to a name by position + name rather than by a name id, since a position's
-- storms span both its current and its retired names.
CREATE TABLE storms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "position" integer NOT NULL,
    name character varying(20) NOT NULL,
    intensity storms_intensity NOT NULL,
    map character varying(200) DEFAULT NULL,        -- track map URL
    year integer NOT NULL,
    -- Set only for the handful of storms whose official spelling differs from the
    -- list entry; '' otherwise.
    correctspelling character varying(10) NOT NULL,
    isstrongest boolean DEFAULT false NOT NULL,     -- strongest storm to carry this name
    -- Combined with positions.suffix into "12W". Set even for a few 'NT' storms, which the
    -- JTWC numbered in post-season reanalysis without ever having tracked them live.
    jtwcnumber integer,
    isfirst boolean DEFAULT false NOT NULL,         -- first storm of its season
    islast boolean DEFAULT false NOT NULL,          -- last storm of its season
    startdate date,
    enddate date,                                   -- NULL while a storm is still ongoing
    CONSTRAINT storms_date_order_check
        CHECK (enddate IS NULL OR startdate IS NULL OR enddate >= startdate),
    CONSTRAINT storms_ibfk_1 FOREIGN KEY ("position")
        REFERENCES positions(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX idx_17761_position ON storms USING btree ("position");

INSERT INTO storms (
    id, "position", name, intensity, map, year, correctspelling,
    isstrongest, jtwcnumber, isfirst, islast, startdate, enddate
)
VALUES (
    591, 19, 'Yagi', '5',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Yagi_2024_track.png/960px-Yagi_2024_track.png',
    2024, '', true, 12, false, false, '2024-08-31', '2024-09-09'
);

-- ---------------------------------------------------------------------------
-- suggestednames — candidate replacements proposed for a retired name
-- ---------------------------------------------------------------------------

-- Several candidates per retired name; ischosen marks the one adopted, which is then
-- mirrored into typhoonnames.replacementname.
CREATE TABLE suggestednames (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nameid bigint NOT NULL,
    replacementname character varying(10) NOT NULL,
    meaning character varying(255) DEFAULT NULL,
    ischosen boolean DEFAULT false NOT NULL,
    image character varying(255) DEFAULT NULL,
    imageauthor character varying,
    imagesourceurl character varying,
    imagelicenseid smallint,
    CONSTRAINT suggestednames_ibfk_1 FOREIGN KEY (nameid)
        REFERENCES typhoonnames(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT suggestednames_imagelicenseid_fkey FOREIGN KEY (imagelicenseid)
        REFERENCES imagelicenses(id)
);

CREATE INDEX idx_17771_nameid ON suggestednames USING btree (nameid);

INSERT INTO suggestednames (
    id, nameid, replacementname, meaning, ischosen, image,
    imageauthor, imagesourceurl, imagelicenseid
)
VALUES (
    152, 19, 'Tomo', 'Puppis; stern', true,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Star_of_India_stern_1.JPG/960px-Star_of_India_stern_1.JPG',
    'BrokenSphere', 'https://commons.wikimedia.org/wiki/File:Star_of_India_stern_1.JPG', 8
);

-- ---------------------------------------------------------------------------
-- Web push
-- ---------------------------------------------------------------------------

-- Created by db/migrations/2026-08-03-web-push.sql, which also installs the storms
-- triggers that fill pushoutbox. See that file for why the names side has no trigger.

CREATE TYPE push_topic AS ENUM ('storms', 'names');

CREATE TYPE pushoutbox_kind AS ENUM (
    'formed', 'intensified', 'strongest', 'seasonfirst', 'seasonlast', 'committee'
);

CREATE TYPE pushoutbox_status AS ENUM ('pending', 'sent', 'cancelled');

-- One row per browser that granted notification permission.
CREATE TABLE pushsubscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint text NOT NULL UNIQUE,  -- push service URL; the browser's identity for this subscription
    p256dh text NOT NULL,           -- client public key
    auth text NOT NULL,             -- client auth secret
    topics push_topic[] NOT NULL DEFAULT ARRAY['storms', 'names']::push_topic[],
    useragent text,
    createdat timestamptz NOT NULL DEFAULT now(),
    updatedat timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pushsubscriptions_topics_not_empty CHECK (cardinality(topics) > 0)
);

CREATE INDEX idx_pushsubscriptions_topics ON pushsubscriptions USING gin (topics);

-- The queue. Rows land here from the storms triggers or from the admin announce button,
-- and stay 'pending' until a drain sends them — which is the window in which a push
-- caused by a typo can still be cancelled.
CREATE TABLE pushoutbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind pushoutbox_kind NOT NULL,
    topic push_topic NOT NULL,
    dedupekey text NOT NULL UNIQUE, -- natural key for the event, e.g. "intensified:591:5"
    title text NOT NULL,
    body text NOT NULL,
    url text NOT NULL,              -- app-relative deep link
    status pushoutbox_status NOT NULL DEFAULT 'pending',
    createdat timestamptz NOT NULL DEFAULT now(),
    sentat timestamptz,
    sentcount integer,
    CONSTRAINT pushoutbox_sentat_requires_sent
        CHECK ((status = 'sent') = (sentat IS NOT NULL))
);

CREATE INDEX idx_pushoutbox_pending ON pushoutbox (createdat) WHERE status = 'pending';
