-- Schema of the typhoon database, with one example row per table.
-- The example rows form a single connected set — position 19 and the name Yagi —
-- so the file loads top to bottom with every foreign key satisfied.

CREATE SCHEMA IF NOT EXISTS catfisha_typhoons;

SET search_path TO catfisha_typhoons, public;

-- Saffir-Simpson category for typhoons ('1'-'5'), below-typhoon strength otherwise.
-- 'MD' (monsoon depression) is not a step on the scale: the JTWC never issued warnings on
-- that storm, so it has no category at all. It sorts first so the enum order still runs
-- weakest to strongest.
CREATE TYPE storms_intensity AS ENUM ('MD', 'TD', 'TS', 'STS', '1', '2', '3', '4', '5');

CREATE TYPE typhoonnames_retirementreason AS ENUM ('destructive', 'language', 'misspell', 'special');

CREATE TABLE imagelicenses (
    id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name character varying NOT NULL UNIQUE,
    url character varying
);

INSERT INTO imagelicenses (id, name, url) OVERRIDING SYSTEM VALUE
VALUES
    (5, 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'),
    (8, 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0');

-- The 140 slots of the Western Pacific naming list. A position is a fixed slot in the
-- rotation, owned by one contributing country. Both typhoonnames and storms hang off it,
-- which is how a storm gets its country without duplicating it per row.
-- Positions 141-143 sit outside the list: they stand for the agency that named a storm in
-- another basin (CPHC, NHC, IMD) before it crossed into the western Pacific.
CREATE TABLE positions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country character varying(20) NOT NULL
);

INSERT INTO positions (id, country)
VALUES (19, 'Japan');

-- Every name that has ever held a position, current or retired. A position accumulates rows
-- over time: the name in rotation today plus each name that was retired out of that slot.
-- isretired distinguishes them.
CREATE TABLE typhoonnames (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(10) NOT NULL,
    meaning character varying(255) NOT NULL,
    tag character varying(40) NOT NULL,             -- category of the meaning, e.g. "Animal", "Flower"
    "position" integer NOT NULL,
    isretired boolean DEFAULT false NOT NULL,
    -- True once a replacement name has actually been selected; a name can be retired
    -- while the committee is still deciding, in which case suggestednames holds the candidates.
    isreplaced boolean DEFAULT false NOT NULL,
    replacementname character varying(10),
    note text,
    language character varying(20) NOT NULL,
    lastyear integer,                               -- final season the name was used; NULL while in rotation
    image character varying(255) DEFAULT NULL,
    description character varying(255),
    imageauthor character varying,
    imagesourceurl character varying,
    imagelicenseid smallint,
    ipa text DEFAULT 'NULL',                        -- default is the literal string 'NULL', not SQL NULL
    originaltext text,                              -- name in its native script, e.g. ヤギ
    pronunciationfile text,                         -- filename under public/, e.g. "Yagi.mp3"
    retirementreason typhoonnames_retirementreason,
    CONSTRAINT typhoonnames_retirementreason_requires_retired
        CHECK ((retirementreason IS NULL) = (NOT isretired)),
    CONSTRAINT typhoonnames_ibfk_1 FOREIGN KEY ("position")
        REFERENCES positions(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT typhoonnames_imagelicenseid_fkey FOREIGN KEY (imagelicenseid)
        REFERENCES imagelicenses(id)
);

CREATE INDEX idx_17781_position ON typhoonnames USING btree ("position");

INSERT INTO typhoonnames (
    id, name, meaning, tag, "position", isretired, isreplaced,
    replacementname, note, language, lastyear, image, description,
    imageauthor, imagesourceurl, imagelicenseid, ipa, originaltext,
    pronunciationfile, retirementreason
)
VALUES (
    19, 'Yagi', 'Capricorn, goat', 'Animal', 19, true, true,
    'Tomo', NULL, 'Japanese', 2024,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Feral_Goats_at_St_Tudno%27s_Churchyard_-_geograph.org.uk_-_2426882.jpg/960px-Feral_Goats_at_St_Tudno%27s_Churchyard_-_geograph.org.uk_-_2426882.jpg',
    NULL, 'David Dixon',
    'https://commons.wikimedia.org/wiki/File:Feral_Goats_at_St_Tudno''s_Churchyard_-_geograph.org.uk_-_2426882.jpg',
    5, '[ja̠ɡʲi]', 'ヤギ', 'Yagi.mp3', 'destructive'
);

-- One row per named storm occurrence. Joined to a name by position + name rather than by a
-- name id, since a position's storms span both its current and its retired names.
CREATE TABLE storms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "position" integer NOT NULL,
    name character varying(20) NOT NULL,
    intensity storms_intensity NOT NULL,
    map character varying(200) DEFAULT NULL,        -- track map URL
    year integer NOT NULL,
    isstrongest boolean DEFAULT false NOT NULL,     -- strongest storm to carry this name
    -- JTWC designation, number plus basin letter, e.g. '12W'. The letter is the basin the
    -- storm formed in, not its naming agency: Li 1994 and Nolo 2026 sit under CPHC (141) but
    -- read 'E'. Set even for a few 'MD' storms, which the JTWC numbered in post-season
    -- reanalysis without ever having tracked them live.
    jtwcdesignation character(3),
    -- JMA international number, "YYnn" for the nn-th storm of season YY, e.g. '2411' for
    -- Yagi 2024. Text, not integer, so the 2000-2009 seasons keep their leading zero ('0919').
    -- NULL for storms that entered the basin already named by another agency, which JMA
    -- numbers only if they are still at tropical-storm strength on arrival.
    jmanumber character(4) UNIQUE,
    isfirst boolean DEFAULT false NOT NULL,         -- first storm of its season
    islast boolean DEFAULT false NOT NULL,          -- last storm of its season
    startdate date NOT NULL,
    enddate date,
    CONSTRAINT storms_date_order_check
        CHECK (enddate IS NULL OR enddate >= startdate),
    CONSTRAINT storms_jtwcdesignation_format_check
        CHECK (jtwcdesignation ~ '^[0-9]{2}[WECB]$'),
    CONSTRAINT storms_ibfk_1 FOREIGN KEY ("position")
        REFERENCES positions(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX idx_17761_position ON storms USING btree ("position");

INSERT INTO storms (
    id, "position", name, intensity, map, year,
    isstrongest, jtwcdesignation, jmanumber, isfirst, islast, startdate, enddate
)
VALUES (
    591, 19, 'Yagi', '5',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Yagi_2024_track.png/960px-Yagi_2024_track.png',
    2024, true, '12W', '2411', false, false, '2024-08-31', '2024-09-09'
);

-- Candidate replacements proposed for a retired name. Several candidates per retired name;
-- ischosen marks the one adopted, which is then mirrored into typhoonnames.replacementname.
CREATE TABLE suggestednames (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nameid bigint NOT NULL,
    replacementname character varying(10) NOT NULL,
    meaning character varying(255) DEFAULT NULL,
    ischosen boolean DEFAULT false NOT NULL,
    image character varying(255) DEFAULT NULL,
    imageauthor character varying,
    imagesourceurl character varying,
    imagelicenseid smallint,
    CONSTRAINT suggestednames_ibfk_1 FOREIGN KEY (nameid)
        REFERENCES typhoonnames(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT suggestednames_imagelicenseid_fkey FOREIGN KEY (imagelicenseid)
        REFERENCES imagelicenses(id)
);

CREATE INDEX idx_17771_nameid ON suggestednames USING btree (nameid);

INSERT INTO suggestednames (
    id, nameid, replacementname, meaning, ischosen, image,
    imageauthor, imagesourceurl, imagelicenseid
)
VALUES (
    152, 19, 'Tomo', 'Puppis; stern', true,
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Star_of_India_stern_1.JPG/960px-Star_of_India_stern_1.JPG',
    'BrokenSphere', 'https://commons.wikimedia.org/wiki/File:Star_of_India_stern_1.JPG', 8
);

-- The trivia shown on the home page, one finished sentence per row. getRandomFact picks one at
-- random; the text is written by hand, not derived from the other tables at read time.
CREATE TABLE facts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text text NOT NULL,
    generatedat timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE facts ENABLE ROW LEVEL SECURITY;

INSERT INTO facts (id, text, generatedat)
VALUES (
    16, 'Yagi is the only name with more than one record-strength storm.',
    '2026-08-13 19:58:40.393675+07'
);
