/**
 * Generates src/app/antd.css: Ant Design's component styles as one static stylesheet.
 *
 * Without it every prerendered page carries its own ~150 KB inline <style> block, which
 * is ~35% of the site's ISR write units for bytes that are identical across pages. The
 * layout links the generated file instead, and AntdRegistry stops inlining in production.
 *
 * Run by `npm run build` (prebuild), so the file can never go stale against the theme.
 * Any Ant Design component the app renders must appear in SURFACE below, or its styles
 * won't be in the stylesheet — `npm run check:antd-css` fails the build if that happens.
 *
 *   node --experimental-strip-types scripts/extract-antd-css.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { createElement as h, type ReactNode } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { ANTD_THEME } from "../src/lib/layout/AntdProvider/theme.ts";

// Ant Design bakes "css-dev-only-do-not-override-" into its class names unless NODE_ENV is
// production when it is first loaded, so antd is imported dynamically after setting it.
process.env.NODE_ENV = "production";

const { createCache, extractStyle, StyleProvider } = await import("@ant-design/cssinjs");
const {
  App,
  AutoComplete,
  Badge,
  Button,
  Carousel,
  ConfigProvider,
  DatePicker,
  Dropdown,
  Empty,
  Form,
  Input,
  Modal,
  Popover,
  Radio,
  Segmented,
  Select,
  Space,
  Spin,
  Switch,
  Table,
  Tooltip,
} = await import("antd");

const OUT = resolve(import.meta.dirname, "../src/app/antd.css");

// Every Ant Design component the app imports. Modal and Dropdown render their styles only
// when open, so they are forced open here rather than mounted in their resting state.
const SURFACE: ReactNode[] = [
  h(Button, { key: "btn-primary", type: "primary" }, "x"),
  h(Button, { key: "btn-default" }, "x"),
  h(Button, { key: "btn-text", type: "text", danger: true }, "x"),
  h(Button, { key: "btn-link", type: "link", loading: true }, "x"),
  h(Input, { key: "input" }),
  h(Input.Search, { key: "input-search" }),
  h(Input.TextArea, { key: "input-textarea" }),
  h(AutoComplete, { key: "autocomplete", options: [{ value: "x" }], open: true }),
  h(Select, { key: "select", options: [{ value: "x", label: "x" }], open: true }),
  h(DatePicker, { key: "datepicker", open: true }),
  h(Segmented, { key: "segmented", options: ["a", "b"] }),
  h(Radio.Group, { key: "radio", options: ["a", "b"], value: "a" }),
  h(Switch, { key: "switch", checked: true }),
  h(Badge, { key: "badge", count: 1 }, h("span", null, "x")),
  h(Empty, { key: "empty" }),
  h(Spin, { key: "spin", spinning: true, size: "large" }, h("div", null, "x")),
  h(Tooltip, { key: "tooltip", open: true, title: "x" }, h("span", null, "x")),
  h(Space, { key: "space" }, "x"),
  h(Carousel, { key: "carousel" }, h("div", { key: "slide" }, "x")),
  h(Popover, { key: "popover", open: true, content: "x" }, h("span", null, "x")),
  h(Dropdown, { key: "dropdown", open: true, menu: { items: [{ key: "1", label: "x" }] } },
    h("span", null, "x")),
  h(Modal, { key: "modal", open: true, getContainer: false }, "x"),
  h(Form, { key: "form" }, h(Form.Item, { label: "x", name: "x" }, h(Input, null))),
  h(Table, {
    key: "table",
    dataSource: [{ key: "1", a: "x" }],
    pagination: { current: 1, pageSize: 10, total: 100 },
    columns: [
      { title: "a", dataIndex: "a", sorter: true, fixed: "left" },
      { title: "b", dataIndex: "b", filters: [{ text: "x", value: "x" }] },
    ],
  }),
];

const cache = createCache();

renderToStaticMarkup(
  h(
    StyleProvider,
    { cache },
    h(ConfigProvider, { theme: ANTD_THEME }, h(App, { component: false }, ...SURFACE)),
  ),
);

const css = extractStyle(cache, { plain: true });

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `/* Generated by scripts/extract-antd-css.ts — do not edit. */\n${css}\n`);

console.log(`extract-antd-css: wrote ${(css.length / 1024).toFixed(1)} KB to ${OUT}`);
